name: Publish Prerelease to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish (Prerelease)
    permissions:
      contents: read
      id-token: write # Required for OIDC
    uses: ./.github/workflows/npm-publish.yml
    with:
      npm_tag: next
      short_sha: ${{ github.sha }}
