name: Publish Release to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build & Publish (Release)
    permissions:
      contents: read
      id-token: write # Required for OIDC
    uses: ./.github/workflows/npm-publish.yml
    with:
      npm_tag: latest
      release_version: ${{ github.ref_name }}
    secrets: inherit
